### ISSUE TITLE
riot 3 support

### ISSUE THREAD

**Issue by mikey0000** [crisward/riot-routehandler#11]
I'm having issues where it won't mount the view. Riot does not find it on the page. All the routes are loading correctly.

**Comment by crisward** [comment]
Sorry not updated it for riot 3 yet. I update riotgrid2 last week. May get onto the route handler this weekend.

**Comment by crisward** [comment]
This is almost complete. I just need to bring in the latest version of riot, run tests, then push this to npm (presuming the fix has worked). Expect a new version next weekend.

**Comment by crisward** [comment]
v3.0 version now been pushed to npm.
