### ISSUE TITLE
Callback support

### ISSUE THREAD

**Issue by gawin** [crisward/riot-routehandler#7]
Page.js supports callback methods.
It would be great of riot-routehandler would also support callbacks.

Right now I'm mounting the routehandler as follows:
`riot.mount('routehandler', {routes: routes, routeroptions: {hashbang:true} });`

Would be great if we can also supply callbacks like this:
`riot.mount('routehandler', {routes: routes, routeroptions: {hashbang:true}, callback: function(){ console.log('route changed') } });`

In our case we are developing a single page app (no surprise there) and need to be able to track users for analytical purposes. Using a callback on the router itself, whenever the route is changed, feels the most appropriate way to deal with this.

**Comment by crisward** [comment]
Have you tried the middleware option? You should be able to use it with the \* route to get the tracking you need.

**Comment by gawin** [comment]
Yes, that was the first thing I tried.

But using the `page('*', callback)` or middleware `page(callback)` as specified in the [Page. js documentation](https://visionmedia.github.io/page.js/) breaks `riot-routehandler` completely. As if the `riot-routehandler` callback is automatically overwritten by the new callback.

```
function myPageCallback(){
  console.log('myPageCallback');
}
page(myPageCallback);
```

or

```
function myPageCallback(){
  console.log('myPageCallback');
}
page('*', myPageCallback);
```

**Comment by crisward** [comment]
Sorry, I probably didn't explain myself very well.

See example here

http://codepen.io/crisward/pen/xwGJpM?editors=1011

notice the 'use' instead of 'tag', this can be given a function to act as middleware.

If you open the console. you'll see how I'm logging out the path clicked, though other data is available inside the ctx object. You also have access to page for redirects etc.

**Comment by gawin** [comment]
Ah, that example solves our issue, awesome @crisward!
