### ISSUE TITLE
Webpack support for Riot 2.*

### ISSUE THREAD

**Issue by mikey0000** [crisward/riot-routehandler#9]
Doesn't play nice with Webpack. Getting the following errors.

```
routehandler.js:7Uncaught Error: Cannot find module "."
```

as well as 

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

seems switching the require check to this solves the issue
```
if(typeof exports === "object" && exports) {
```

**Comment by crisward** [comment]
Thanks for spotting this. I use browserify with this and don't have any issues, though I'll be happy to update. Plan to do a riot 3.0 update soon, so will include this as part of the update. Will maintain a riot 2.* version for a while as I'm still using riot 2.* in all my projects so far.

**Comment by mikey0000** [comment]
Thanks, really appreciate it!

**Comment by crisward** [comment]
I'll aim to do this as part of the riot 3.0 update. Should be done next weekend.

**Comment by crisward** [comment]
I've just changed the check for v3.0.1 and pushed to npm.
Please re-open if this hasn't fixed it. Please note this requires riot 3.0.2. If you need this for riot 2 let me know.

**Comment by mikey0000** [comment]
Yes please to riot 2 support, unfortunately I'm stuck on 2 because of a dep

**Comment by crisward** [comment]
I've pushed that update to the Riot2 branch too.

**Comment by crisward** [comment]
Also push to npm - version 1.2.4

**Comment by crisward** [comment]
Please re-open if you still have problems
